# syntax=docker/dockerfile:1
#
# One Dockerfile, one dependency stage, four targets.
#
# This replaces four per-app Dockerfiles that each maintained their own list of workspace
# manifests. `bun install --frozen-lockfile` validates the lockfile against the WHOLE
# workspace, so any image whose deps stage is missing a package.json reads as drift and the
# install refuses. That broke the deploy three separate times — once when packages/db and
# packages/baileys-auth arrived, once for packages/core, and once for apps/web, where the
# *gateway* image failed because of a manifest it does not even use.
#
# With a single shared `deps` stage there is exactly one list to keep current, and a missing
# manifest fails every target at once rather than one at random.

# ---------------------------------------------------------------------------------------
FROM oven/bun:1.2-alpine AS deps
WORKDIR /app
# Manifests only, so dependency installation caches independently of source changes.
COPY package.json bun.lock ./
COPY packages/contracts/package.json packages/contracts/
COPY packages/core/package.json packages/core/
COPY packages/db/package.json packages/db/
COPY packages/baileys-auth/package.json packages/baileys-auth/
COPY apps/api/package.json apps/api/
COPY apps/gateway/package.json apps/gateway/
COPY apps/webhook-worker/package.json apps/webhook-worker/
COPY apps/web/package.json apps/web/
RUN bun install --frozen-lockfile

# ---------------------------------------------------------------------------------------
# api — Bun. Stateless; redeploys freely.
FROM oven/bun:1.2-alpine AS api
WORKDIR /app
ENV NODE_ENV=production PORT=3001
COPY --from=deps /app/node_modules ./node_modules
COPY package.json tsconfig.base.json ./
COPY packages/contracts ./packages/contracts
COPY packages/core ./packages/core
COPY packages/db ./packages/db
COPY apps/api ./apps/api
ARG GIT_COMMIT=dev
ENV GIT_COMMIT=$GIT_COMMIT
EXPOSE 3001
USER bun
HEALTHCHECK --interval=30s --timeout=3s --start-period=10s --retries=3 \
  CMD wget -qO- http://127.0.0.1:3001/health || exit 1
CMD ["bun", "apps/api/src/index.ts"]

# ---------------------------------------------------------------------------------------
# gateway — NODE, not Bun (PLAN.md §2 / Q26). It is the one process expected to hold WhatsApp
# sockets open for days, and a runtime incompatibility there surfaces as an unexplained
# day-three disconnect rather than a startup crash. Baileys declares engines: node >= 20.
FROM node:22-alpine AS gateway
WORKDIR /app
ENV NODE_ENV=production PORT=3002
COPY --from=deps /app/node_modules ./node_modules
COPY package.json tsconfig.base.json ./
COPY packages/contracts ./packages/contracts
COPY packages/core ./packages/core
COPY packages/db ./packages/db
COPY packages/baileys-auth ./packages/baileys-auth
COPY apps/gateway ./apps/gateway
EXPOSE 3002
HEALTHCHECK --interval=30s --timeout=3s --start-period=20s --retries=3 \
  CMD wget -qO- http://127.0.0.1:3002/health || exit 1
# Through node rather than node_modules/.bin: those entries are generated by bun, and
# depending on a cross-runtime shim inside a node image is a variable worth removing.
CMD ["node", "./node_modules/tsx/dist/cli.mjs", "apps/gateway/src/server.ts"]

# ---------------------------------------------------------------------------------------
# webhook-worker — stateless consumer.
FROM node:22-alpine AS webhook-worker
WORKDIR /app
ENV NODE_ENV=production
COPY --from=deps /app/node_modules ./node_modules
COPY package.json tsconfig.base.json ./
COPY packages/core ./packages/core
COPY packages/db ./packages/db
COPY apps/webhook-worker ./apps/webhook-worker
CMD ["node", "./node_modules/tsx/dist/cli.mjs", "apps/webhook-worker/src/index.ts"]

# ---------------------------------------------------------------------------------------
# web — Next.js dashboard.
FROM node:22-alpine AS web-builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY package.json tsconfig.base.json ./
COPY packages ./packages
COPY apps/web ./apps/web
# Next inlines NEXT_PUBLIC_* at build time, so Clerk's publishable key must be present here.
# It is publishable by definition; the secret key is injected at runtime only.
ARG NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY
ENV NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=$NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY
ENV NEXT_TELEMETRY_DISABLED=1
# Cap the heap so an over-large build fails loudly rather than thrashing swap.
ENV NODE_OPTIONS=--max-old-space-size=3072
WORKDIR /app/apps/web
# webpack, not Turbopack: the shared packages use NodeNext `./thing.js` specifiers pointing at
# .ts sources, required by the Node consumers, and Turbopack cannot map those back.
RUN node ../../node_modules/next/dist/bin/next build --webpack

FROM node:22-alpine AS web
WORKDIR /app
ENV NODE_ENV=production PORT=3000 HOSTNAME=0.0.0.0
# Standalone output carries its own minimal node_modules.
COPY --from=web-builder /app/apps/web/.next/standalone ./
COPY --from=web-builder /app/apps/web/.next/static ./apps/web/.next/static
EXPOSE 3000
CMD ["node", "apps/web/server.js"]
