import type { Metadata, Viewport } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const sans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const mono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "wapi — WhatsApp over HTTP",
  description:
    "Self-hosted WhatsApp REST API. Link a number, get an API key, send and receive messages over HTTP.",
  /**
   * Icons, generated by the `icongen` skill and rebuildable from
   * `public/icon.config.json`.
   *
   * The light/dark pair is selected with `media` on the link rather than by the inline script
   * the generator suggests. A script would work, but it costs a render-blocking tag in the root
   * layout of every page to swap an icon — and the declarative form degrades correctly: a
   * browser that ignores `media` takes the first matching icon rather than none.
   *
   * `.ico` is listed first and without `media` because that is the fallback for the browsers
   * that do not read SVG favicons at all.
   */
  icons: {
    icon: [
      { url: "/favicon.ico", sizes: "32x32" },
      {
        url: "/favicon.svg",
        type: "image/svg+xml",
        media: "(prefers-color-scheme: light)",
      },
      {
        url: "/favicon-dark.svg",
        type: "image/svg+xml",
        media: "(prefers-color-scheme: dark)",
      },
    ],
    apple: "/apple-touch-icon.png",
  },
  manifest: "/site.webmanifest",
};

/**
 * `themeColor` lives on the viewport export, not on metadata — Next moved it, and leaving it
 * on `metadata` is silently ignored rather than an error.
 *
 * The values are inverted relative to the scheme on purpose: the icon tile is near-black in
 * light mode and near-white in dark, so the browser chrome matches the tile rather than the
 * page behind it.
 */
export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  themeColor: [
    { color: "#0a0a0a", media: "(prefers-color-scheme: light)" },
    { color: "#fafafa", media: "(prefers-color-scheme: dark)" },
  ],
};

/**
 * The root layout deliberately renders no chrome.
 *
 * The landing page and the dashboard want different navigation, and a shared header forced
 * both into a compromise. Each surface brings its own via <AppNav /> or its own <Nav />.
 */
export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${sans.variable} ${mono.variable}`}>{children}</body>
      </html>
    </ClerkProvider>
  );
}
