/**
 * Emit `src/types.gen.ts` from the OpenAPI document.
 *
 * ## Why generate types but hand-write the client
 *
 * Every OpenAPI client generator — openapi-typescript, hey-api, orval,
 * swagger-typescript-api — derives method names from `operationId`. Ours are mechanical path
 * transliterations, because they are generated from the mirrored spec:
 *
 *     postApiWhatsappSessionsWhatsappSessionRegenerateKey
 *     getApiWhatsappSessionsWhatsappSessionMessageLogs
 *
 * No generator turns those into `sessions.keys.regenerate(id)`. Running one would buy correct
 * types at the cost of a surface nobody wants to call, and renaming 30 operations by hand in a
 * config file is the same work as writing 30 methods, minus the ability to group them.
 *
 * So the split is: **types are generated, ergonomics are written.** The generated file is the
 * contract; the hand-written client is the API. `ops/check-sdk-in-sync.mjs` fails CI when they
 * drift, which is what makes "update the SDK when an endpoint changes" mechanical rather than a
 * rule someone has to remember.
 *
 * The OpenAPI document is the input rather than the Zod schemas because it is the artifact the
 * Go and Python SDKs will also read. A generator written against `@wapi/contracts` internals
 * would not transfer.
 *
 * Run: bun run --cwd sdk/typescript generate
 */
import { writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { buildOpenApiDocument } from "@wapi/contracts";

const HERE = dirname(fileURLToPath(import.meta.url));
const OUT = resolve(HERE, "../src/types.gen.ts");

type Schema = Record<string, unknown>;

/** `postApiMessagesReact` → `PostApiMessagesReact`, used to name the emitted types. */
const pascal = (s: string) => s.charAt(0).toUpperCase() + s.slice(1);

/**
 * JSON Schema → a TypeScript type expression.
 *
 * Deliberately small: the schemas here come from Zod via `z.toJSONSchema`, so the shapes are
 * objects, arrays, primitives, enums, `anyOf` unions and `$ref`s to the four failure envelopes.
 * A general-purpose converter would be more code and no more correct for this input.
 */
function toType(schema: Schema | undefined, indent = 0): string {
  if (!schema) return "unknown";

  const ref = schema["$ref"];
  if (typeof ref === "string") return ref.split("/").pop() ?? "unknown";

  // Zod emits unions as anyOf; `?paginated=true` responses are one of these.
  const anyOf = (schema["anyOf"] ?? schema["oneOf"]) as Schema[] | undefined;
  if (Array.isArray(anyOf)) {
    return anyOf.map((s) => toType(s, indent)).join(" | ");
  }

  const enumValues = schema["enum"] as unknown[] | undefined;
  if (Array.isArray(enumValues)) {
    return enumValues.map((v) => JSON.stringify(v)).join(" | ");
  }
  // `z.literal(true)` becomes `const`, which is how `success` is pinned.
  if ("const" in schema) return JSON.stringify(schema["const"]);

  const type = schema["type"];

  if (Array.isArray(type)) {
    // e.g. ["string", "null"] from `.nullable()`.
    return type.map((t) => toType({ ...schema, type: t }, indent)).join(" | ");
  }

  switch (type) {
    case "string":
      return "string";
    case "integer":
    case "number":
      return "number";
    case "boolean":
      return "boolean";
    case "null":
      return "null";
    case "array":
      return `${toType(schema["items"] as Schema, indent)}[]`;
    case "object": {
      const props = (schema["properties"] ?? {}) as Record<string, Schema>;
      const entries = Object.entries(props);
      if (entries.length === 0) return "Record<string, unknown>";
      const required = new Set((schema["required"] as string[] | undefined) ?? []);
      const pad = "  ".repeat(indent + 1);
      const body = entries
        .map(([key, value]) => {
          const optional = required.has(key) ? "" : "?";
          // Quote keys that are not valid identifiers — `retry_after` is fine, but be safe.
          const name = /^[A-Za-z_$][\w$]*$/.test(key) ? key : JSON.stringify(key);
          return `${pad}${name}${optional}: ${toType(value, indent + 1)};`;
        })
        .join("\n");
      return `{\n${body}\n${"  ".repeat(indent)}}`;
    }
    default:
      return "unknown";
  }
}

const doc = buildOpenApiDocument("https://api.wapi.crafter.run") as {
  components: { schemas: Record<string, Schema> };
  paths: Record<string, Record<string, Schema>>;
};

const out: string[] = [
  "// GENERATED by sdk/typescript/scripts/generate-types.ts — do not edit by hand.",
  "// Run `bun run --cwd sdk/typescript generate` after changing any route or response schema.",
  "//",
  "// Derived from the OpenAPI document, which is itself emitted from the Zod contracts the",
  "// server validates against — so these types cannot drift from the implementation without CI",
  "// noticing (see ops/check-sdk-in-sync.mjs).",
  "",
];

// The four failure envelopes, named once and referenced by every operation.
for (const [name, schema] of Object.entries(doc.components.schemas)) {
  const description = schema["description"];
  if (typeof description === "string") out.push(`/** ${description} */`);
  out.push(`export type ${name} = ${toType(schema)};`, "");
}

/** One entry per operation, so the hand-written client can reference exact shapes. */
const operations: string[] = [];

for (const [path, methods] of Object.entries(doc.paths)) {
  for (const [method, op] of Object.entries(methods)) {
    const operationId = op["operationId"] as string;
    const name = pascal(operationId);
    const summary = op["summary"] as string | undefined;

    const body = (op["requestBody"] as Schema | undefined)?.["content"] as
      | Record<string, { schema?: Schema }>
      | undefined;
    const bodySchema = body?.["application/json"]?.schema;
    if (bodySchema) {
      out.push(`/** Request body for \`${method.toUpperCase()} ${path}\`. */`);
      out.push(`export type ${name}Body = ${toType(bodySchema)};`, "");
    }

    const params = (op["parameters"] ?? []) as { in: string; name: string; schema?: Schema }[];
    const query = params.filter((p) => p.in === "query");
    if (query.length > 0) {
      out.push(`/** Query parameters for \`${method.toUpperCase()} ${path}\`. */`);
      const fields = query
        .map((p) => `  ${p.name}?: ${toType(p.schema)};`)
        .join("\n");
      out.push(`export type ${name}Query = {\n${fields}\n};`, "");
    }

    const responses = op["responses"] as Record<string, Schema>;
    const successCode = Object.keys(responses).find((c) => c.startsWith("2"));
    const successSchema = (
      (responses[successCode ?? ""]?.["content"] as
        | Record<string, { schema?: Schema }>
        | undefined)?.["application/json"]?.schema
    );
    if (successSchema) {
      out.push(`/** ${summary ?? `Response for ${method.toUpperCase()} ${path}`}. */`);
      out.push(`export type ${name}Response = ${toType(successSchema)};`, "");
    }

    operations.push(
      `  ${operationId}: { method: "${method.toUpperCase()}"; path: "${path}"; status: ${successCode ?? "200"} };`,
    );
  }
}

out.push(
  "/**",
  " * Every operation, its verb, its path template and the status it answers with.",
  " *",
  " * The client does not read this at runtime; it exists so a reviewer can see the whole surface",
  " * in one place, and so a removed endpoint shows up as a type error rather than a 404.",
  " */",
  "export type Operations = {",
  ...operations.sort(),
  "};",
  "",
);

writeFileSync(OUT, out.join("\n"), "utf8");
console.log(`wrote ${OUT} — ${operations.length} operations`);
