// GENERATED by sdk/typescript/scripts/generate-types.ts — do not edit by hand.
// Run `bun run --cwd sdk/typescript generate` after changing any route or response schema.
//
// Derived from the OpenAPI document, which is itself emitted from the Zod contracts the
// server validates against — so these types cannot drift from the implementation without CI
// noticing (see ops/check-sdk-in-sync.mjs).

/** Failure decided by a route handler. */
export type Failure = {
  success: false;
  error: string;
};

/** Failure decided by middleware: authentication, subscription gating. */
export type FrameworkFailure = {
  success: false;
  message: string;
  errors?: Record<string, unknown>;
};

/** Validation failure. `errors` maps each rejected field to its messages. */
export type ValidationFailure = {
  success: false;
  message: string;
  errors?: Record<string, unknown>;
};

/** Rate limited. Deliberately carries no `success` key. */
export type ThrottleFailure = {
  message: string;
  retry_after: number;
};

/** Fetch one session, including its API key and webhook secret. */
export type GetApiWhatsappSessionsWhatsappSessionResponse = {
  success: true;
  data: {
    id: number;
    name: string;
    phone_number: string;
    status: string;
    account_protection: boolean;
    log_messages: boolean;
    webhook_url: string | null;
    webhook_enabled: boolean;
    webhook_events: string[] | null;
    created_at: string;
    updated_at: string;
    api_key: string | null;
    webhook_secret: string | null;
  };
};

/** Request body for `PUT /api/whatsapp-sessions/{whatsappSession}`. */
export type PutApiWhatsappSessionsWhatsappSessionBody = {
  name?: string;
  phone_number?: string;
  account_protection?: boolean;
  log_messages?: boolean;
  webhook_url?: string;
  webhook_enabled?: boolean;
  webhook_events?: unknown[];
  read_incoming_messages?: boolean;
  auto_reject_calls?: boolean;
  ignore_groups?: boolean;
  ignore_channels?: boolean;
  ignore_broadcasts?: boolean;
  proxy_url?: string;
  always_online?: boolean;
};

/** Update a session's settings, webhook config or proxy. */
export type PutApiWhatsappSessionsWhatsappSessionResponse = {
  success: true;
  data: {
    id: number;
    name: string;
    phone_number: string;
    status: string;
    account_protection: boolean;
    log_messages: boolean;
    webhook_url: string | null;
    webhook_enabled: boolean;
    webhook_events: string[] | null;
    created_at: string;
    updated_at: string;
    api_key: string | null;
    webhook_secret: string | null;
  };
};

/** Query parameters for `GET /api/contacts`. */
export type GetApiContactsQuery = {
  paginated?: boolean;
  page?: number;
  limit?: number;
};

/** Contacts known to this session. */
export type GetApiContactsResponse = {
  success: true;
  data: {
    jid: string;
    id?: string;
    name: string | null;
    notify: string | null;
    verifiedName: string | null;
    imgUrl: string | null;
    status: string | null;
    phoneNumber?: string | null;
    lid?: string | null;
  }[];
} | {
  success: true;
  data: {
    items: {
      jid: string;
      id?: string;
      name: string | null;
      notify: string | null;
      verifiedName: string | null;
      imgUrl: string | null;
      status: string | null;
      phoneNumber?: string | null;
      lid?: string | null;
    }[];
    pagination: {
      page: number;
      limit: number;
      total: number;
      totalPages: number;
    };
  };
};

/** Request body for `PUT /api/contacts`. */
export type PutApiContactsBody = {
  jid: string;
  fullName?: string;
  saveOnPrimaryAddressbook?: boolean;
};

/** putApiContacts. */
export type PutApiContactsResponse = {
  success: true;
  data: {
    fullName: string | null;
    jid: string;
  };
};

/** Fetch one contact. */
export type GetApiContactsContactPhoneNumberResponse = {
  success: true;
  data: {
    id: string;
    jid?: string;
    name: string | null;
    notify: string | null;
    verifiedName: string | null;
    imgUrl: string | null;
    status: string | null;
    phoneNumber?: string | null;
    lid?: string | null;
  };
};

/** getApiContactsContactPhoneNumberPicture. */
export type GetApiContactsContactPhoneNumberPictureResponse = {
  success: true;
  data: {
    imgUrl: string | null;
  };
};

/** Query parameters for `GET /api/groups`. */
export type GetApiGroupsQuery = {
  paginated?: boolean;
  page?: number;
  limit?: number;
};

/** Groups this session belongs to. */
export type GetApiGroupsResponse = {
  success: true;
  data: {
    jid: string;
    id?: string;
    name: string;
    subject?: string;
    imgUrl: string | null;
    owner?: string | null;
    creation?: number | null;
    desc?: string | null;
    participants?: {
      jid: string;
      isAdmin: boolean;
      isSuperAdmin: boolean;
      id?: string;
      admin?: string | null;
    }[];
  }[];
} | {
  success: true;
  data: {
    items: {
      jid: string;
      id?: string;
      name: string;
      subject?: string;
      imgUrl: string | null;
      owner?: string | null;
      creation?: number | null;
      desc?: string | null;
      participants?: {
        jid: string;
        isAdmin: boolean;
        isSuperAdmin: boolean;
        id?: string;
        admin?: string | null;
      }[];
      notify?: null;
      verifiedName?: null;
    }[];
    pagination: {
      page: number;
      limit: number;
      total: number;
      totalPages: number;
    };
  };
};

/** Request body for `POST /api/groups`. */
export type PostApiGroupsBody = {
  name: string;
  participants?: string[];
};

/** Create a group. */
export type PostApiGroupsResponse = {
  success: true;
  data: {
    jid: string;
    id?: string;
    name?: string;
    subject: string;
    imgUrl?: string | null;
    owner?: string | null;
    creation?: number | null;
    desc?: string | null;
    participants: {
      jid: string;
      isAdmin: boolean;
      isSuperAdmin: boolean;
      id?: string;
      admin?: string | null;
    }[];
  };
};

/** Group subject, description, owner and participants. */
export type GetApiGroupsGroupJidMetadataResponse = {
  success: true;
  data: {
    jid: string;
    id?: string;
    name?: string;
    subject: string;
    imgUrl?: string | null;
    owner?: string | null;
    creation?: number | null;
    desc?: string | null;
    participants: {
      jid: string;
      isAdmin: boolean;
      isSuperAdmin: boolean;
      id?: string;
      admin?: string | null;
    }[];
  };
};

/** Participants of a group. */
export type GetApiGroupsGroupJidParticipantsResponse = {
  success: true;
  data: {
    jid?: string;
    isAdmin?: boolean;
    isSuperAdmin?: boolean;
    id: string;
    admin?: string | null;
  }[];
};

/** getApiLidFromPnPn. */
export type GetApiLidFromPnPnResponse = {
  success: true;
  data: {
    lid: string;
  };
};

/** Fetch a sent message by its integer msgId. */
export type GetApiMessagesMsgIdInfoResponse = {
  success: true;
  data: {
    remoteJid: string | null;
    id: string | null;
    msgId: number;
    key: unknown;
    message: unknown;
    messageTimestamp: string;
    status: number;
  };
};

/** Check whether a number is registered on WhatsApp. */
export type GetApiOnWhatsappContactIdentifierResponse = {
  success: true;
  data: {
    exists: boolean;
    jid?: string | null;
  };
};

/** getApiPnFromLidLid. */
export type GetApiPnFromLidLidResponse = {
  success: true;
  data: {
    pn: string;
  };
};

/** Connection state of the session the API key belongs to. */
export type GetApiStatusResponse = {
  status: string;
};

/** WhatsApp identity behind the session key, including its LID. */
export type GetApiUserResponse = {
  success: true;
  data: {
    id: string;
    name: string | null;
    lid: string | null;
  };
};

/** List every WhatsApp session on the account. */
export type GetApiWhatsappSessionsResponse = {
  success: true;
  data: {
    id: number;
    name: string;
    phone_number: string;
    status: string;
    account_protection: boolean;
    log_messages: boolean;
    webhook_url: string | null;
    webhook_enabled: boolean;
    webhook_events: string[] | null;
    created_at: string;
    updated_at: string;
  }[];
};

/** Request body for `POST /api/whatsapp-sessions`. */
export type PostApiWhatsappSessionsBody = {
  name: string;
  phone_number: string;
  account_protection: boolean;
  log_messages: boolean;
  webhook_url?: string;
  webhook_enabled?: boolean;
  webhook_events?: unknown[];
  read_incoming_messages?: boolean;
  auto_reject_calls?: boolean;
  ignore_groups?: boolean;
  ignore_channels?: boolean;
  ignore_broadcasts?: boolean;
  proxy_url?: string;
  always_online?: boolean;
};

/** Create a WhatsApp session and issue its API key. */
export type PostApiWhatsappSessionsResponse = {
  success: true;
  data: {
    id: number;
    name: string;
    phone_number: string;
    status: string;
    account_protection: boolean;
    log_messages: boolean;
    webhook_url: string | null;
    webhook_enabled: boolean;
    webhook_events: string[] | null;
    created_at: string;
    updated_at: string;
    api_key: string | null;
    webhook_secret: string | null;
  };
};

/** Query parameters for `GET /api/whatsapp-sessions/{whatsappSession}/message-logs`. */
export type GetApiWhatsappSessionsWhatsappSessionMessageLogsQuery = {
  page?: number;
  per_page?: number;
};

/** Paginated log of messages sent through a session. */
export type GetApiWhatsappSessionsWhatsappSessionMessageLogsResponse = {
  success: true;
  data: {
    current_page: number;
    data: {
      id: string;
      whatsapp_session_id: string;
      to: string | null;
      content: string | null;
      status: string | null;
      failed_reason: string | null;
      created_at: string | null;
      updated_at: string | null;
    }[];
    first_page_url: string;
    from: number | null;
    last_page: number;
    last_page_url: string;
    next_page_url: string | null;
    path: string;
    per_page: number;
    prev_page_url: string | null;
    to: number | null;
    total: number;
  };
};

/** Fetch the current QR string for a session awaiting a scan. */
export type GetApiWhatsappSessionsWhatsappSessionQrcodeResponse = {
  success: true;
  data: {
    qrCode: string;
  };
};

/** postApiContactsContactPhoneNumberBlock. */
export type PostApiContactsContactPhoneNumberBlockResponse = {
  success: true;
  data: {
    message: string;
  };
};

/** postApiContactsContactPhoneNumberUnblock. */
export type PostApiContactsContactPhoneNumberUnblockResponse = {
  success: true;
  data: {
    message: string;
  };
};

/** Request body for `POST /api/decrypt-media`. */
export type PostApiDecryptMediaBody = {
  data: Record<string, unknown>;
};

/** Decrypt an inbound media node and return a URL valid for one hour. */
export type PostApiDecryptMediaResponse = {
  success: true;
  publicUrl: string;
};

/** Request body for `POST /api/groups/{groupJid}/participants/add`. */
export type PostApiGroupsGroupJidParticipantsAddBody = {
  participants: unknown[];
};

/** Add participants to a group. */
export type PostApiGroupsGroupJidParticipantsAddResponse = {
  success: true;
  data: {
    status: number;
    jid: string;
    message: string;
  }[];
};

/** Request body for `POST /api/groups/{groupJid}/participants/remove`. */
export type PostApiGroupsGroupJidParticipantsRemoveBody = {
  participants: unknown[];
};

/** Remove participants from a group. */
export type PostApiGroupsGroupJidParticipantsRemoveResponse = {
  success: true;
  data: {
    status: number;
    jid: string;
    message: string;
  }[];
};

/** Request body for `POST /api/messages/read`. */
export type PostApiMessagesReadBody = {
  key: Record<string, unknown>;
};

/** Mark a received message as read. */
export type PostApiMessagesReadResponse = {
  success: true;
  data: {
    status: string;
  };
};

/** Request body for `POST /api/send-message`. */
export type PostApiSendMessageBody = {
  to: string;
  text?: string;
  imageUrl?: string;
  videoUrl?: string;
  documentUrl?: string;
  audioUrl?: string;
  stickerUrl?: string;
  contact?: Record<string, unknown>;
  location?: Record<string, unknown>;
  mentions?: unknown[];
  fileName?: string;
  poll?: Record<string, unknown>;
  replyTo?: number;
  viewOnce?: boolean;
};

/** Send a message. One endpoint for every message type. */
export type PostApiSendMessageResponse = {
  success: true;
  data: {
    msgId: number;
    jid: string;
    status: string;
  };
};

/** Request body for `POST /api/upload`. */
export type PostApiUploadBody = {
  base64?: string;
  mimetype?: string;
  "Request Body"?: unknown;
};

/** Upload a file and get a public URL, as raw bytes or base64. */
export type PostApiUploadResponse = {
  success: true;
  publicUrl: string;
};

/** Request body for `POST /api/whatsapp-sessions/{whatsappSession}/connect`. */
export type PostApiWhatsappSessionsWhatsappSessionConnectBody = {
  linkMethod?: string;
};

/** Begin linking, returning a QR code when one is ready. */
export type PostApiWhatsappSessionsWhatsappSessionConnectResponse = {
  success: true;
  data: {
    status: string;
    qrCode?: string;
    message?: string;
  };
};

/** Close the socket without unlinking the device. */
export type PostApiWhatsappSessionsWhatsappSessionDisconnectResponse = {
  success: true;
  data: {
    status: string;
    message: string;
  };
};

/** Issue a new API key, invalidating the old one. */
export type PostApiWhatsappSessionsWhatsappSessionRegenerateKeyResponse = {
  success: true;
  api_key: string;
};

/** Reconnect a live session using its stored credentials. */
export type PostApiWhatsappSessionsWhatsappSessionRestartResponse = {
  success: true;
  message: string;
};

/** Request body for `POST /api/messages/react`. */
export type PostApiMessagesReactBody = {
  key: {
    id: string;
    remoteJid: string;
    fromMe?: boolean;
    participant?: string;
  };
  emoji: string;
};

/** React to a message, or clear a reaction with an empty emoji. */
export type PostApiMessagesReactResponse = {
  success: true;
  data: {
    id: string | null;
    emoji: string;
  };
};

/** Request body for `POST /api/sandbox/sessions`. */
export type PostApiSandboxSessionsBody = {
  name: string;
};

/** Create a sandbox session — a fake number on a fake WhatsApp. */
export type PostApiSandboxSessionsResponse = {
  success: true;
  data: {
    id: number;
    name: string;
    phone_number: string;
    status: string;
    account_protection: boolean;
    log_messages: boolean;
    webhook_url: string | null;
    webhook_enabled: boolean;
    webhook_events: string[] | null;
    created_at: string;
    updated_at: string;
    api_key: string | null;
    webhook_secret: string | null;
  };
};

/** Request body for `POST /api/sandbox/inbound`. */
export type PostApiSandboxInboundBody = {
  from?: string;
  text: string;
};

/** Fabricate an inbound message on a sandbox session. */
export type PostApiSandboxInboundResponse = {
  success: true;
  data: {
    key: unknown;
  };
};

/** Request body for `POST /api/sandbox/scan`. */
export type PostApiSandboxScanBody = Record<string, unknown>;

/** Complete pairing on a sandbox session awaiting its fake QR. */
export type PostApiSandboxScanResponse = {
  success: true;
  data: {
    status: string;
  };
};

/**
 * Every operation, its verb, its path template and the status it answers with.
 *
 * The client does not read this at runtime; it exists so a reviewer can see the whole surface
 * in one place, and so a removed endpoint shows up as a type error rather than a 404.
 */
export type Operations = {
  deleteApiWhatsappSessionsWhatsappSession: { method: "DELETE"; path: "/api/whatsapp-sessions/{whatsappSession}"; status: 204 };
  getApiContacts: { method: "GET"; path: "/api/contacts"; status: 200 };
  getApiContactsContactPhoneNumber: { method: "GET"; path: "/api/contacts/{contactPhoneNumber}"; status: 200 };
  getApiContactsContactPhoneNumberPicture: { method: "GET"; path: "/api/contacts/{contactPhoneNumber}/picture"; status: 200 };
  getApiGroups: { method: "GET"; path: "/api/groups"; status: 200 };
  getApiGroupsGroupJidMetadata: { method: "GET"; path: "/api/groups/{groupJid}/metadata"; status: 200 };
  getApiGroupsGroupJidParticipants: { method: "GET"; path: "/api/groups/{groupJid}/participants"; status: 200 };
  getApiLidFromPnPn: { method: "GET"; path: "/api/lid-from-pn/{pn}"; status: 200 };
  getApiMessagesMsgIdInfo: { method: "GET"; path: "/api/messages/{msgId}/info"; status: 200 };
  getApiOnWhatsappContactIdentifier: { method: "GET"; path: "/api/on-whatsapp/{contact_identifier}"; status: 200 };
  getApiPnFromLidLid: { method: "GET"; path: "/api/pn-from-lid/{lid}"; status: 200 };
  getApiStatus: { method: "GET"; path: "/api/status"; status: 200 };
  getApiUser: { method: "GET"; path: "/api/user"; status: 200 };
  getApiWhatsappSessions: { method: "GET"; path: "/api/whatsapp-sessions"; status: 200 };
  getApiWhatsappSessionsWhatsappSession: { method: "GET"; path: "/api/whatsapp-sessions/{whatsappSession}"; status: 200 };
  getApiWhatsappSessionsWhatsappSessionMessageLogs: { method: "GET"; path: "/api/whatsapp-sessions/{whatsappSession}/message-logs"; status: 200 };
  getApiWhatsappSessionsWhatsappSessionQrcode: { method: "GET"; path: "/api/whatsapp-sessions/{whatsappSession}/qrcode"; status: 200 };
  postApiContactsContactPhoneNumberBlock: { method: "POST"; path: "/api/contacts/{contactPhoneNumber}/block"; status: 200 };
  postApiContactsContactPhoneNumberUnblock: { method: "POST"; path: "/api/contacts/{contactPhoneNumber}/unblock"; status: 200 };
  postApiDecryptMedia: { method: "POST"; path: "/api/decrypt-media"; status: 200 };
  postApiGroups: { method: "POST"; path: "/api/groups"; status: 201 };
  postApiGroupsGroupJidParticipantsAdd: { method: "POST"; path: "/api/groups/{groupJid}/participants/add"; status: 200 };
  postApiGroupsGroupJidParticipantsRemove: { method: "POST"; path: "/api/groups/{groupJid}/participants/remove"; status: 200 };
  postApiMessagesReact: { method: "POST"; path: "/api/messages/react"; status: 200 };
  postApiMessagesRead: { method: "POST"; path: "/api/messages/read"; status: 200 };
  postApiSandboxInbound: { method: "POST"; path: "/api/sandbox/inbound"; status: 200 };
  postApiSandboxScan: { method: "POST"; path: "/api/sandbox/scan"; status: 200 };
  postApiSandboxSessions: { method: "POST"; path: "/api/sandbox/sessions"; status: 201 };
  postApiSendMessage: { method: "POST"; path: "/api/send-message"; status: 200 };
  postApiUpload: { method: "POST"; path: "/api/upload"; status: 200 };
  postApiWhatsappSessions: { method: "POST"; path: "/api/whatsapp-sessions"; status: 201 };
  postApiWhatsappSessionsWhatsappSessionConnect: { method: "POST"; path: "/api/whatsapp-sessions/{whatsappSession}/connect"; status: 200 };
  postApiWhatsappSessionsWhatsappSessionDisconnect: { method: "POST"; path: "/api/whatsapp-sessions/{whatsappSession}/disconnect"; status: 200 };
  postApiWhatsappSessionsWhatsappSessionRegenerateKey: { method: "POST"; path: "/api/whatsapp-sessions/{whatsappSession}/regenerate-key"; status: 200 };
  postApiWhatsappSessionsWhatsappSessionRestart: { method: "POST"; path: "/api/whatsapp-sessions/{whatsappSession}/restart"; status: 200 };
  putApiContacts: { method: "PUT"; path: "/api/contacts"; status: 200 };
  putApiWhatsappSessionsWhatsappSession: { method: "PUT"; path: "/api/whatsapp-sessions/{whatsappSession}"; status: 200 };
};
